### ISSUE TITLE
hlint in nvim/coc/hls

### ISSUE THREAD

**Issue by samhh** [samhh/dotfiles#122]

**Comment by samhh** [comment]
https://github.com/haskell/haskell-language-server/issues/32

**Comment by expipiplus1** [comment]
I wonder if this will require updating the (or implementing a new) coc.nvim haskell-ide-engine plugin?

I have this working quite well for HIE with this https://github.com/expipiplus1/vscode-hie-server/ but am looking forward to being able to use HLS, (but really have no desire to rebase my changes on the latest haskell plugin which seems to have changed quite a bit)

**Comment by samhh** [comment]
Solved by deferring linting matters to ALE: https://github.com/samhh/dotfiles/commit/62ed3a1a971bb0cb182ca312703226b5bc704b58
