### ISSUE TITLE
pacdiff w/ neovim and user config

### ISSUE THREAD

**Issue by samhh** [samhh/dotfiles#175]
`pacdiff` is packaged with `pacman-contrib`, but I can't use it because:

- It searches for `vim`, which I don't have installed.
- If I symlink that (with e.g. `neovim-symlinks`), the editor config is completely broken given the use of `sudo`.

**Comment by samhh** [comment]
If/when this is working, this script can be removed: https://github.com/samhh/dotfiles/commit/d57ae25a5578007a5440f66692367378ec5a01d5

**Comment by samhh** [comment]
https://github.com/lambdalisue/suda.vim

**Comment by xse** [comment]
> * It searches for `vim`, which I don't have installed.
> * If I symlink that (with e.g. `neovim-symlinks`), the editor config is completely broken given the use of `sudo`.

mine works great i tried like

```
export DIFFPROG="nvim -d $1"
alias vim="nvim"
```

in zshrc and launching the whole thing with `sudo -E`

**Comment by samhh** [comment]
I vaguely recall that there's a security risk with `sudo -E`, but my Google-fu is failing me today.

**Comment by samhh** [comment]
I still can't remember what I was on about ^, so setting `DIFFPROG` works a treat, thanks @xse! https://github.com/samhh/dotfiles/commit/8517247a6a0e305ce9d6df5e6214f6dbc330cc08

`$ sudo -E pacdiff`

**Comment by YodaEmbedding** [comment]
Presumably, malicious actors can inject something into the *user* environment variables, e.g.

```bash
LPROMPT="rm -rf / --no-preserve-groot"
```

...so that something like `sudo -E bash` will execute that.

**Comment by hashworks** [comment]
You can also allow it to keep specific variables.
```
$ sudo visudo /etc/sudoers.d/00-env
Defaults env_keep+="EDITOR DIFFPROG"
```
